<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cfop', function (Blueprint $table) {
            $table->id();
            $table->string('name', 400);
            $table->char('code', 4)->unique();
            $table->tinyInteger('operation_type')->comment('[0..1] 0-Entrada, 1-Saída');            
            $table->timestamps();
        });

        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1101', 'Compra para industrialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1102', 'Compra para comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1116', 'Compra para industrialização originada de encomenda para recebimento futuro', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1117', 'Compra para comercialização originada de encomenda para recebimento futuro', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1124', 'Industrialização efetuada por outra empresa', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1126', 'Compra para utilização na prestação de serviço', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1151', 'Transferência para industrialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1152', 'Transferência para comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1153', 'Transferência de energia elétrica para distribuição', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1154', 'Transferência para utilização na prestação de serviço', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1201', 'Devolução de venda de produção do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1205', 'Anulação de valor relativo à prestação de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1206', 'Anulação de valor relativo à prestação de serviço de transporte', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1207', 'Anulação de valor relativo à venda de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1208', 'Devolução de produção do estabelecimento, remetida em transferência', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1251', 'Compra de energia elétrica para distribuição ou comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1252', 'Compra de energia elétrica por estabelecimento industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1253', 'Compra de energia elétrica por estabelecimento comercial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1256', 'Compra de energia elétrica por estabelecimento de produtor rural', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1257', 'Compra de energia elétrica para consumo por demanda contratada', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1302', 'Aquisição de serviço de comunicação por estabelecimento industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1303', 'Aquisição de serviço de comunicação por estabelecimento comercial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1352', 'Aquisição de serviço de transporte por estabelecimento industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1353', 'Aquisição de serviço de transporte por estabelecimento comercial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1451', 'Retorno de animal do estabelecimento produtor', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1452', 'Retorno de insumo não utilizado na produção', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1501', 'Entrada de mercadoria recebida com fim específico de exportação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1551', 'Compra de bem para o ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1552', 'Transferência de bem do ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1553', 'Devolução de venda de bem do ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1556', 'Compra de material para uso ou consumo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1557', 'Transferência de material para uso ou consumo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1601', 'Recebimento, por transferência, de crédito de ICMS', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1602', 'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1603', 'Ressarcimento de ICMS retido por substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1604', 'Lançamento do crédito relativo à compra de bem para o ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1901', 'Entrada para industrialização por encomenda', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1902', 'Retorno de mercadoria remetida para industrialização por encomenda', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1904', 'Retorno de remessa para venda fora do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1908', 'Entrada de bem por conta de contrato de comodato', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1909', 'Retorno de bem remetido por conta de contrato de comodato', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1910', 'Entrada de bonificação, doação ou brinde', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1911', 'Entrada de amostra grátis', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1912', 'Entrada de mercadoria ou bem recebido para demonstração', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1913', 'Retorno de mercadoria ou bem remetido para demonstração', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1914', 'Retorno de mercadoria ou bem remetido para exposição ou feira', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1920', 'Entrada de vasilhame ou sacaria', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1921', 'Retorno de vasilhame ou sacaria', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('1949', 'Outra entrada de mercadoria ou prestação de serviço não especificada', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2101', 'Compra para industrialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2102', 'Compra para comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2116', 'Compra para industrialização originada de encomenda para recebimento futuro', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2117', 'Compra para comercialização originada de encomenda para recebimento futuro', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2124', 'Industrialização efetuada por outra empresa', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2126', 'Compra para utilização na prestação de serviço', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2151', 'Transferência para industrialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2152', 'Transferência para comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2153', 'Transferência de energia elétrica para distribuição', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2154', 'Transferência para utilização na prestação de serviço', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2201', 'Devolução de venda de produção do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2205', 'Anulação de valor relativo à prestação de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2206', 'Anulação de valor relativo à prestação de serviço de transporte', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2207', 'Anulação de valor relativo à venda de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2208', 'Devolução de produção do estabelecimento, remetida em transferência', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2251', 'Compra de energia elétrica para distribuição ou comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2252', 'Compra de energia elétrica por estabelecimento industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2253', 'Compra de energia elétrica por estabelecimento comercial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2256', 'Compra de energia elétrica por estabelecimento de produtor rural', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2257', 'Compra de energia elétrica para consumo por demanda contratada', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2302', 'Aquisição de serviço de comunicação por estabelecimento industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2303', 'Aquisição de serviço de comunicação por estabelecimento comercial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2352', 'Aquisição de serviço de transporte por estabelecimento industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2353', 'Aquisição de serviço de transporte por estabelecimento comercial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2501', 'Entrada de mercadoria recebida com fim específico de exportação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2551', 'Compra de bem para o ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2552', 'Transferência de bem do ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2553', 'Devolução de venda de bem do ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2556', 'Compra de material para uso ou consumo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2557', 'Transferência de material para uso ou consumo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2603', 'Ressarcimento de ICMS retido por substituição tributária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2901', 'Entrada para industrialização por encomenda', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2902', 'Retorno de mercadoria remetida para industrialização por encomenda', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2904', 'Retorno de remessa para venda fora do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2908', 'Entrada de bem por conta de contrato de comodato', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2909', 'Retorno de bem remetido por conta de contrato de comodato', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2910', 'Entrada de bonificação, doação ou brinde', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2911', 'Entrada de amostra grátis', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2912', 'Entrada de mercadoria ou bem recebido para demonstração', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2913', 'Retorno de mercadoria ou bem remetido para demonstração', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2914', 'Retorno de mercadoria ou bem remetido para exposição ou feira', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2920', 'Entrada de vasilhame ou sacaria', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2921', 'Retorno de vasilhame ou sacaria', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('2949', 'Outra entrada de mercadoria ou prestação de serviço não especificado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3101', 'Compra para industrialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3102', 'Compra para comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3126', 'Compra para utilização na prestação de serviço', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3127', 'Compra para industrialização sob o regime de drawback', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3201', 'Devolução de venda de produção do estabelecimento', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3205', 'Anulação de valor relativo à prestação de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3206', 'Anulação de valor relativo à prestação de serviço de transporte', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3207', 'Anulação de valor relativo à venda de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3211', 'Devolução de venda de produção do estabelecimento sob o regime de drawback', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3251', 'Compra de energia elétrica para distribuição ou comercialização', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3352', 'Aquisição de serviço de transporte por estabelecimento industrial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3353', 'Aquisição de serviço de transporte por estabelecimento comercial', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3503', 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3551', 'Compra de bem para o ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3553', 'Devolução de venda de bem do ativo imobilizado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3556', 'Compra de material para uso ou consumo', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3930', 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('3949', 'Outra entrada de mercadoria ou prestação de serviço não especificado', '0')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5101', 'Venda de produção do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5102', 'Venda de mercadoria adquirida ou recebida de terceiros', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5105', 'Venda de produção do estabelecimento que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5112', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5124', 'Industrialização efetuada para outra empresa', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5151', 'Transferência de produção do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5152', 'Transferência de mercadoria adquirida ou recebida de terceiros', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5153', 'Transferência de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5155', 'Transferência de produção do estabelecimento, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5201', 'Devolução de compra para industrialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5202', 'Devolução de compra para comercialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5205', 'Anulação de valor relativo a aquisição de serviço de comunicação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5206', 'Anulação de valor relativo a aquisição de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5207', 'Anulação de valor relativo à compra de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5208', 'Devolução de mercadoria recebida em transferência para industrialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5209', 'Devolução de mercadoria recebida em transferência para comercialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5210', 'Devolução de compra para utilização na prestação de serviço', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5251', 'Venda de energia elétrica para distribuição ou comercialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5252', 'Venda de energia elétrica para estabelecimento industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5253', 'Venda de energia elétrica para estabelecimento comercial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5256', 'Venda de energia elétrica para estabelecimento de produtor rural', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5257', 'Venda de energia elétrica para consumo por demanda contratada', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5258', 'Venda de energia elétrica a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5302', 'Prestação de serviço de comunicação a estabelecimento industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5303', 'Prestação de serviço de comunicação a estabelecimento comercial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5307', 'Prestação de serviço de comunicação a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5352', 'Prestação de serviço de transporte a estabelecimento industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5353', 'Prestação de serviço de transporte a estabelecimento comercial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5356', 'Prestação de serviço de transporte a estabelecimento de produtor rural', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5357', 'Prestação de serviço de transporte a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5405', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5451', 'Remessa de animal e de insumo para estabelecimento produtor', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5501', 'Remessa de produção do estabelecimento, com fim específico de exportação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5503', 'Devolução de mercadoria recebida com fim específico de exportação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5551', 'Venda de bem do ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5552', 'Transferência de bem do ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5553', 'Devolução de compra de bem para o ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5556', 'Devolução de compra de material de uso ou consumo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5557', 'Transferência de material de uso ou consumo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5601', 'Transferência de crédito de ICMS acumulado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5602', 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5603', 'Ressarcimento de ICMS retido por substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5901', 'Remessa para industrialização por encomenda', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5902', 'Retorno de mercadoria utilizada na industrialização por encomenda', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5904', 'Remessa para venda fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5905', 'Remessa para depósito fechado ou armazém geral', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5908', 'Remessa de bem por conta de contrato de comodato', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5909', 'Retorno de bem recebido por conta de contrato de comodato', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5910', 'Remessa em bonificação, doação ou brinde', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5911', 'Remessa de amostra grátis', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5912', 'Remessa de mercadoria ou bem para demonstração', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5913', 'Retorno de mercadoria ou bem recebido para demonstração', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5914', 'Remessa de mercadoria ou bem para exposição ou feira', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5915', 'Remessa de mercadoria ou bem para conserto ou reparo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5917', 'Remessa de mercadoria em consignação mercantil ou industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5920', 'Remessa de vasilhame ou sacaria', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5921', 'Devolução de vasilhame ou sacaria', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria,', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5927', 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5928', 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5931', 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('5949', 'Outra saída de mercadoria ou prestação de serviço não especificado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6101', 'Venda de produção do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6102', 'Venda de mercadoria adquirida ou recebida de terceiros', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6105', 'Venda de produção do estabelecimento que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6107', 'Venda de produção do estabelecimento, destinada a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6108', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6112', 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6124', 'Industrialização efetuada para outra empresa', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6151', 'Transferência de produção do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6152', 'Transferência de mercadoria adquirida ou recebida de terceiros', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6153', 'Transferência de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6155', 'Transferência de produção do estabelecimento, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6201', 'Devolução de compra para industrialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6202', 'Devolução de compra para comercialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6205', 'Anulação de valor relativo a aquisição de serviço de comunicação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6206', 'Anulação de valor relativo a aquisição de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6207', 'Anulação de valor relativo à compra de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6208', 'Devolução de mercadoria recebida em transferência para industrialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6209', 'Devolução de mercadoria recebida em transferência para comercialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6210', 'Devolução de compra para utilização na prestação de serviço', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6251', 'Venda de energia elétrica para distribuição ou comercialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6252', 'Venda de energia elétrica para estabelecimento industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6253', 'Venda de energia elétrica para estabelecimento comercial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6256', 'Venda de energia elétrica para estabelecimento de produtor rural', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6257', 'Venda de energia elétrica para consumo por demanda contratada', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6258', 'Venda de energia elétrica a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6302', 'Prestação de serviço de comunicação a estabelecimento industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6303', 'Prestação de serviço de comunicação a estabelecimento comercial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6307', 'Prestação de serviço de comunicação a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6352', 'Prestação de serviço de transporte a estabelecimento industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6353', 'Prestação de serviço de transporte a estabelecimento comercial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6356', 'Prestação de serviço de transporte a estabelecimento de produtor rural', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6357', 'Prestação de serviço de transporte a não contribuinte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6404', 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6501', 'Remessa de produção do estabelecimento, com fim específico de exportação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6503', 'Devolução de mercadoria recebida com fim específico de exportação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6551', 'Venda de bem do ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6552', 'Transferência de bem do ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6553', 'Devolução de compra de bem para o ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6556', 'Devolução de compra de material de uso ou consumo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6557', 'Transferência de material de uso ou consumo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6603', 'Ressarcimento de ICMS retido por substituição tributária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6901', 'Remessa para industrialização por encomenda', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6902', 'Retorno de mercadoria utilizada na industrialização por encomenda', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6904', 'Remessa para venda fora do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6905', 'Remessa para depósito fechado ou armazém geral', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6908', 'Remessa de bem por conta de contrato de comodato', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6909', 'Retorno de bem recebido por conta de contrato de comodato', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6910', 'Remessa em bonificação, doação ou brinde', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6911', 'Remessa de amostra grátis', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6912', 'Remessa de mercadoria ou bem para demonstração', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6913', 'Retorno de mercadoria ou bem recebido para demonstração', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6914', 'Remessa de mercadoria ou bem para exposição ou feira', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6915', 'Remessa de mercadoria ou bem para conserto ou reparo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6917', 'Remessa de mercadoria em consignação mercantil ou industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6920', 'Remessa de vasilhame ou sacaria', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6921', 'Devolução de vasilhame ou sacaria', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6931', 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('6949', 'Outra saída de mercadoria ou prestação de serviço não especificado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7101', 'Venda de produção do estabelecimento', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7102', 'Venda de mercadoria adquirida ou recebida de terceiros', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7105', 'Venda de produção do estabelecimento, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7127', 'Venda de produção do estabelecimento sob o regime de drawback', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7201', 'Devolução de compra para industrialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7202', 'Devolução de compra para comercialização', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7205', 'Anulação de valor relativo à aquisição de serviço de comunicação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7206', 'Anulação de valor relativo a aquisição de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7207', 'Anulação de valor relativo à compra de energia elétrica', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7210', 'Devolução de compra para utilização na prestação de serviço', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7211', 'Devolução de compras para industrialização sob o regime de drawback', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7251', 'Venda de energia elétrica para o exterior', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7358', 'Prestação de serviço de transporte', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7501', 'Exportação de mercadorias recebidas com fim específico de exportação', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7551', 'Venda de bem do ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7553', 'Devolução de compra de bem para o ativo imobilizado', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7556', 'Devolução de compra de material de uso ou consumo', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7930', 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária', '1')");
        DB::statement("INSERT INTO `cfop` (code, name, operation_type) VALUES ('7949', 'Outra saída de mercadoria ou prestação de serviço não especificado', '1')");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cfop');
    }
};
